apiVersion: v1
kind: Secret
metadata:
  name: tenant-secret
  namespace: marketplace
type: Opaque
stringData:
  JWT_SECRET: auth_ms_jwt_secret
  DB_HOST: capstone-database.cdjpvyodvvjq.us-east-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_USER: postgres
  DB_PASSWORD: rubentanoey1
  DB_NAME: tenant
  REDIS_PASSWORD: redis
