apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-deployment
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant
  template:
    metadata:
      labels:
        app: tenant
    spec:
      containers:
        - name: tenant
          image: rubentanoey/marketplace-tenant:v1
          ports:
            - containerPort: 8003
          env:
            - name: TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: tenant-config
                  key: TENANT_ID
            - name: PORT
              value: "8003"
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: tenant-config
                  key: AUTH_SERVICE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: tenant-secret
                  key: JWT_SECRET
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: tenant-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: tenant-secret
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: tenant-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tenant-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: tenant-secret
                  key: DB_NAME
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: products-secret
                  key: REDIS_URL
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: products-secret
                  key: REDIS_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: products-secret
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: products-secret
                  key: REDIS_PORT
            - name: REDIS_DB
              valueFrom:
                secretKeyRef:
                  name: products-secret
                  key: REDIS_DB
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"