apiVersion: v1
kind: ConfigMap
metadata:
  name: products-config
  namespace: marketplace
data:
  TENANT_ID: "47dd6b24-0b23-46b0-a662-776158d089ba"
  PORT: "8002"
  AUTH_SERVICE_URL: "http://auth.marketplace.svc.cluster.local:8000/api"
  TENANT_SERVICE_URL: "http://tenant.marketplace.svc.cluster.local:8003/api"
  DUMMY_PRODUCT_ID: "5edb2fc6-9193-4ea7-93f1-ff9b4d3b408c"
  REDIS_HOST: redis-cache.marketplace.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  # REDIS_URL: redis://:redis@10.43.188.179.marketplace.svc.cluster.local:6379/0
  REDIS_URL: "redis://:redis@10.43.188.179:6379/0"
