apiVersion: v1
kind: Service
metadata:
  name: products
  namespace: marketplace
spec:
  selector:
    app: products
  ports:
    - port: 8002
      targetPort: 8002
      nodePort: 30002
  type: NodePort
