apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: rubentanoey/marketplace-products:v1
          ports:
            - containerPort: 8002
          env:
            - name: TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: products-config
                  key: TENANT_ID
            - name: PORT
              value: "8002"
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: products-config
                  key: AUTH_SERVICE_URL
            - name: TENANT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: products-config
                  key: TENANT_SERVICE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: products-secret
                  key: JWT_SECRET
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: products-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: products-secret
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: products-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: products-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: products-secret
                  key: DB_NAME
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1"
