apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: marketplace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: rubentanoey/marketplace-authentication:latest
          imagePullPolicy: Always 
          ports:
            - containerPort: 8000
          env:
            - name: TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: TENANT_ID
            - name: ADMIN_TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: ADMIN_TENANT_ID
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: PORT
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: NODE_ENV
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_SECRET
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: ADMIN_JWT_SECRET
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: DB_NAME
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"