version: "3.8"

services:
  products:
    container_name: products
    build: .
    ports:
      - "8002:8002"
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - AUTH_SERVICE_URL=http://auth:8000/api/auth
      - TENANT_SERVICE_URL=http://tenant:8003/api/tenant
      - JWT_SECRET=auth_ms_jwt_secret
      - DB_HOST=db-products
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=products
      - ADMIN_TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - DUMMY_PRODUCT_ID=5edb2fc6-9193-4ea7-93f1-ff9b4d3b408c
      - REDIS_PASSWORD=redis
      - REDIS_HOST=host.docker.internal
    depends_on:
      - db-products
    networks:
      - marketplace_network

  db-products:
    image: postgres:latest
    container_name: db-products
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - marketplace_network
  redis:
    image: redis:7.2-alpine
    container_name: redis
    command: redis-server --requirepass redis
    ports:
      - "6379:6379"
    networks:
      - marketplace_network

networks:
  marketplace_network:
    external: false

volumes:
  postgres_data:
