apiVersion: v1
kind: Service
metadata:
  name: wishlist
  namespace: marketplace
spec:
  selector:
    app: wishlist
  ports:
    - port: 8004
      targetPort: 8004
      nodePort: 30005
  type: NodePort
