apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-deployment
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wishlist
  template:
    metadata:
      labels:
        app: wishlist
    spec:
      containers:
        - name: wishlist
          image: rubentanoey/marketplace-wishlist:v1
          ports:
            - containerPort: 8004
          env:
            - name: TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: wishlist-config
                  key: TENANT_ID
            - name: PORT
              value: "8004"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: wishlist-secret
                  key: JWT_SECRET
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: wishlist-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: wishlist-secret
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: wishlist-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wishlist-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wishlist-secret
                  key: DB_NAME
