apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
  namespace: marketplace
data:
  TENANT_ID: "47dd6b24-0b23-46b0-a662-776158d089ba"
  PORT: "8001"
  PRODUCT_SERVICE_URL: "http://products.marketplace.svc.cluster.local:8002/api"
