apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: marketplace
spec:
  selector:
    app: orders
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30004
  type: NodePort
