apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: rubentanoey/marketplace-orders:latest
          ports:
            - containerPort: 8001
          env:
            - name: TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: orders-config
                  key: TENANT_ID
            - name: PORT
              value: "8001"
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: orders-config
                  key: PRODUCT_SERVICE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: JWT_SECRET
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: DB_NAME
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: REDIS_PORT
            - name: REDIS_DB
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: REDIS_DB
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: REDIS_URL
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: REDIS_PASSWORD
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "256Mi"
